name: .NET CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x' # Specify the .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    # Run Unit Tests
    - name: Run Unit Tests
      run: dotnet test ./test/PaymentGateway.Api.UnitTests/ --no-restore --verbosity normal

    # Run Domain Tests
    - name: Run Integration Tests
      run: dotnet test ./test/PaymentGateway.Domain.UnitTests/ --no-restore --verbosity normal

    # Run Domain Tests
    - name: Run Integration Tests
      run: dotnet test ./test/PaymentGateway.IntegrationTests/ --no-restore --verbosity normal

